### ISSUE TITLE
Docker enviroment for develop

### ISSUE THREAD

**Issue by ingluife** [flyve-mdm/docker-environment#21]
Hi, @flyve-mdm/backend-development 

For develop GLPI is required configure an environment in the host machine with all required it. This is a disadvantage by the time necessary in this process.

**Describe the solution you'd like**
Configure containers docker for develop, where everything is ready to work. Use docker compose for configure this enviroment.

**Additional context**
This enviroment must have a web server, database server and PHP as minimun requires.

**Comment by ingluife** [comment]
Hi, @flyve-mdm/backend-development.

I have a blocking, when trying docker build. In the .env file there are one variable GLPI_SOURCE. This variable is escaped when loaded the environment and not execute correctly the git clone. This is happening before to composer install.

I go to trying set variable static and see the result.

**Comment by ingluife** [comment]
Hi, @flyve-mdm/backend-development.

I'm configuring the glpi install and i found a error when is executing the git clone. This is the print screen of result:

![git-clone-error](https://user-images.githubusercontent.com/17582750/41067198-b293d4a2-69b2-11e8-84d9-43c1ffea3f4d.png)

**Comment by btry** [comment]
Not enough clue about the error. There is a protocol error related to HTTPS, but I cannot tell more. 

Maybe a package related to SSL/TLS is not up to date ?

**Comment by ingluife** [comment]
According to some post, the problem is related to cloning by http/https. It that recomended is cloning by ssh protocol instead. I'm testing some change in the docker environment for trying found the best solution

**Comment by btry** [comment]
Try  git@github.com:organization/repository

**Comment by ingluife** [comment]
Hi, @flyve-mdm/backend-development.

I modified the ssl Verific of git for the issue previous and not found the solution. I go to change the way to get the GLPI code and finish the environment configuration.
For this environment i using a bash script into .sh file configuration.

**Comment by ingluife** [comment]
Hi, @flyve-mdm/backend-development.

I modified the way for clone to ssh. In the docker-compose is shared to .ssh directory of host machine with the docker container. This is valid for Mac and Linux. Also i go to configure a vhost after that change the web server by default in this repo.

**Comment by ingluife** [comment]
Hi @flyve-mdm/backend-development.

I changed the web server in this docker compose. I configured its vhost.config and image docker in Dockerfile.
Now i have a issue in the docker build. This error suggested add ServerName in the vhost.conf.
I did it.

![captura de pantalla 2018-06-11 a la s 6 13 08 p m](https://user-images.githubusercontent.com/17582750/41260044-d71953fc-6da3-11e8-9821-a96150c1037b.png)

**Comment by DIOHz0r** [comment]
That server's FQD must be set on httpd.conf, it is not a big issue to solve or to make the web server works.

**Comment by ingluife** [comment]
Hi @flyve-mdm/backend-development.

I finished the environment for GLPI develop.

NOTES: 
- This is tested only in Linux, Specificly Ubuntu 16.04
- If you will to cloning by SSH  you must have your ssh key configured in ~/.ssh host directory

It's ready for be tested.

This docker environment have:

- Server web APACHE2
- PHP7 Language
- Server database MYSQL
- PHPMyadmin

Its configuration process is easy. Only runing a command in the project's root:
`docker-compose up --build`
and Configure your hosts file. This are the params for the hosts file:
`172.26.0.31 www.develop-glpi.local`

This is GLPI Running into Docker Container.
![image](https://user-images.githubusercontent.com/17582750/41379010-ce15c330-6f2e-11e8-8087-3b5448ee4d59.png)

The instalation process execute automaticaly actions of glpi's repository cloning and `composer install` command.
When this docker is build show a log like this:
![image](https://user-images.githubusercontent.com/17582750/41379657-88fcad02-6f30-11e8-8f38-849dc20f91d8.png)
![image](https://user-images.githubusercontent.com/17582750/41379970-8962c136-6f31-11e8-864b-9e66ed91b5a0.png)


After finish the instalation and configured the hosts file, you can to access in the browser:
http://www.develop-glpi.local
![image](https://user-images.githubusercontent.com/17582750/41380004-a54ffb66-6f31-11e8-8021-7b2784235ac1.png)

In database configuration:

![image](https://user-images.githubusercontent.com/17582750/41380023-b8fbe062-6f31-11e8-9608-13a98c5b7dbd.png)

**Comment by rafaelje** [comment]
@ingluife I like the result, IMO the URL can be short instead www.develop-glpi.local could be dev-glpi.local by default

**Comment by ajsb85** [comment]
Hi, @ingluife 
And use HTTPS and for the domain I suggest https://dev.glpi.local

**Comment by btry** [comment]
Needs automation of generating a certificate (self signed)

**Comment by ingluife** [comment]
Ok, we can do it for next release if it's really necesary in the develop environment.

**Comment by ingluife** [comment]
Hi @flyve-mdm/backend-development.

I did the modifications suggested:
- Add environment variable SERVER_NAME
- Add environment variable DEFAULT TIME ZONE as UTC

Also, i did others improvements in the docker-compose:
- add variables for the configuration host port mapped
- add variable for the HOMEPATH and Document root in VirtualHost

Today i did found the solution for the issue of this docker environment in Mac.
Do happened it's that the apache configuration in the host have reserved the port :80, and when i trying build the container in this port the request is refused.

The solution, extracted of https://github.com/docker/for-mac/issues/1869#issuecomment-358104522, is remove the line:
`<string>echo "rdr pass proto tcp from any to any port {80,8080} -> 127.0.0.1 port 8080" | pfctl -a "com.apple/260.HttpFwdFirewall" -Ef - &amp;&amp; echo "rdr pass proto tcp from any to any port {443,8443} -> 127.0.0.1 port 8443" | pfctl -a "com.apple/261.HttpFwdFirewall" -Ef - &amp;&amp; sysctl -w net.inet.ip.forwarding=1</string>`

in the file **/Library/LaunchDaemons/co.echo.httpdfwd.plist** of host machine.

After this, GLPI's running perfectly in the port :80 in the Mac.

![image](https://user-images.githubusercontent.com/17582750/41442532-b458665a-7005-11e8-9a29-6b1d99631760.png)

**NOTE: The configuration of domain in the hosts file for Mac is like this:**
`27.0.0.1 dev.glpi.local` 

It's recomended stopping all services that's runing in the ports 80, 8080, 3306 and 9000 in the host machine before build the containers, or change the ports configuration in .env file.
