### ISSUE TITLE
Docker compose install fails on glpi-php

### ISSUE THREAD

**Issue by kevinohara80** [flyve-mdm/docker-environment#45]
**Describe the bug**
The docker-compose process of the installation fails with the following message:

**"ERROR: Service 'glpi-php' failed to build: cannot normalize nothing"**

**To Reproduce**
1. Clone repo from Github and follow the [instructions](http://flyve.org/docker-environment/howtos/installation)
2. After running `docker-compose up --build`, you'll see a mysqli.so warning then the error message. Logs are below.

**Expected behavior**
Should install and start without error using the docker-compose installation

**Desktop (please complete the following information):**
 - OS: MacOSX 10.12.6

**Additional context**
Here are the final logs from the docker-compose step:

```bash
3164975 1560 -rwxr-xr-x 1 root root 1596984 Aug 30 15:09 /tmp/pear/temp/pear-build-defaultuserRFBUhL/install-xdebug-2.6.1/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so

Build process completed successfully
Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so'
install ok: channel://pecl.php.net/xdebug-2.6.1
configuration option "php_ini" is not set to php.ini location
You should add "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so" to php.ini
Removing intermediate container 0478458f66f8
 ---> 01ba07550a19
Step 56/67 : RUN docker-php-ext-enable xdebug
 ---> Running in a7c19f7c9e84
Removing intermediate container a7c19f7c9e84
 ---> f2493a62c65c
Step 57/67 : RUN docker-php-ext-enable mysqli
 ---> Running in 560e73a744ab

warning: mysqli (mysqli.so) is already loaded!

Removing intermediate container 560e73a744ab
 ---> 39fbca4592fe
Step 58/67 : WORKDIR $GLPIPATH
ERROR: Service 'glpi-php' failed to build: cannot normalize nothing
```

**Comment by LunaticTian** [comment]
The same problem is still encountered and has not been resolved.
