### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/docker-environment#56]
**Describe the solution you'd like**
The last update made on the proyect has changed some build stepts so we need to update the documentation. 

Some changes to be made are:

- Requirenments, update minimun matrix requirement compatiblity: Docker 1.13.0+ and Docker compose 1.10.0+
- Installation, stept 6 Configure GLPI is nood needed anymore because the build installa everything needed. We could add some information of how to login using the default GLPI credentials.
- How it Works, in 2. Glpi-PHP the NodeJS component was removed.

**Comment by Naylin15** [comment]
Solved in #57

Closing this issue
