### ISSUE TITLE
Can't start docker environment

### ISSUE THREAD

**Issue by iorfmer** [flyve-mdm/docker-environment#61]
I follow instructions to install docker environment. The problem is in point 4, I perform docker-compose command:

docker-compose up --build
  
### Observed Results:

froi_mercade@mdm-sagaci:~/docker-environment/docker$ docker-compose up --build
WARNING: The MYSQL_TAG variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The HOST_SERVER_DB_PORT variable is not set. Defaulting to a blank string.
WARNING: The MOSQUITTO_TAG variable is not set. Defaulting to a blank string.
WARNING: The HOST_SERVER_MOSQUITTO_PORT variable is not set. Defaulting to a blank string.
WARNING: The HOST_SERVER_MOSQUITTO_PORT_TLS variable is not set. Defaulting to a blank string.
WARNING: The APACHE_TAG variable is not set. Defaulting to a blank string.
WARNING: The HOST_SERVER_NAME variable is not set. Defaulting to a blank string.
WARNING: The GLPIPATH variable is not set. Defaulting to a blank string.
WARNING: The HOST_SERVER_WEB_PORT variable is not set. Defaulting to a blank string.
WARNING: The PHP_TAG variable is not set. Defaulting to a blank string.
WARNING: The GLPI_DB_NAME_TEST variable is not set. Defaulting to a blank string.
WARNING: The GLPI_DB_NAME_UPGRADE_TEST variable is not set. Defaulting to a blank string.
WARNING: The GLPI_DB_NAME variable is not set. Defaulting to a blank string.
WARNING: The GLPI_BRANCH variable is not set. Defaulting to a blank string.
WARNING: The GLPI_SOURCE variable is not set. Defaulting to a blank string.
WARNING: The CLONNING_METHOD variable is not set. Defaulting to a blank string.
WARNING: The DEFAULT_TIME_ZONE variable is not set. Defaulting to a blank string.
WARNING: The FLYVEMDM_BRANCH variable is not set. Defaulting to a blank string.
WARNING: The FLYVEMDM_SOURCE variable is not set. Defaulting to a blank string.
WARNING: The FLYVEMDM_PATH variable is not set. Defaulting to a blank string.
WARNING: The FUSIONINVENTORY_BRANCH variable is not set. Defaulting to a blank string.
WARNING: The FUSIONINVENTORY_SOURCE variable is not set. Defaulting to a blank string.
WARNING: The FUSIONINVENTORY_PATH variable is not set. Defaulting to a blank string.
WARNING: The HOST_CONFIG_SSH_PATH variable is not set. Defaulting to a blank string.
WARNING: The HOST_ADMIN_DB variable is not set. Defaulting to a blank string.
ERROR: The Compose file './../docker-compose.yml' is invalid because:
services.glpi-mosquitto.ports is invalid: Port ranges don't match in length
services.glpi-dbmysql.ports is invalid: Port ranges don't match in length
services.glpi-apache.ports is invalid: Port ranges don't match in length
services.glpi-phpmyadmin.ports is invalid: Port ranges don't match in length
services.glpi-mosquitto.ports is invalid: Port ranges don't match in length

Any help on this?

Many thanks.

**Comment by ajsb85** [comment]
Hi, @iorfmer 
Are you already found the solution, right?

**Comment by iorfmer** [comment]
Yes, it is. Many thanks anyway!

We have have another issue in the web mdm dashboard. May I open another
issue? Or can i ask you by mail?

Kind regards.

**Comment by ajsb85** [comment]
Yes please, fill a new issue to help you.
https://github.com/flyve-mdm/web-mdm-dashboard/issues/new
You can also join us in the Telegram group for a fast support of the community.

**Comment by iorfmer** [comment]
Thanks, done!

**Comment by Revathinandu** [comment]
@iorfmer what was the solution for the first issue?

**Comment by ajsb85** [comment]
@Revathinandu  set the environment vars
